/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./src/worker-configuration.d.ts --include-runtime false` (hash: 5f32fe4fea096b3e53b8e55fb0b9ff70)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../.svelte-kit/cloudflare/_worker");
	}
	interface Env {
		UPLOADS: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		BUILDING_NAME: "בנימין 11, נהריה";
		BUILDING_PHONES: "ועד בית: 050-302-4414";
		ADMIN_PASSWORD: string;
		SESSION_SECRET: string;
		WEATHER_LAT: string;
		WEATHER_LON: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BUILDING_NAME" | "BUILDING_PHONES" | "ADMIN_PASSWORD" | "SESSION_SECRET" | "WEATHER_LAT" | "WEATHER_LON">> {}
}
